version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html  # Serve frontend static files
    networks:
      - webnet

  app:
    build:
      context: ./backend  # Point to the backend directory where the Dockerfile is located
      dockerfile: Dockerfile  # This is optional but explicit
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount the backend directory
    networks:
      - webnet

networks:
  webnet:
