version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app           # Mount the backend folder
      - ./frontend:/app/frontend  # Mount the frontend folder
    networks:
      - webnet

networks:
  webnet:
